### ISSUE TITLE
Cannot install python3-oxenmq

### ISSUE THREAD

**Issue by AlexanderEpolite** [oxen-io/session-pysogs#107]
i'm getting this error when attempting to install the oxen proxy package:
```
Package python3-oxenmq is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-oxenmq' has no installation candidate
```

any workarounds?  running ubuntu 22.04

**Comment by jagerman** [comment]
Thanks for the report.  It seems I messed up the jammy packaging of python3-oxenmq. I've fixed it now and pushed the proper packages to the jammy deb repo; an `apt update` and you should be good to install it now.

**Comment by rauldipeas** [comment]
I'm facing the same error when I try to install `sogs-standalone` on an ARM machine.
