### ISSUE TITLE
Getting error when viewing the group URL (qrencode+Python3.10 compatibility problem)

### ISSUE THREAD

**Issue by digitalblur** [oxen-io/session-pysogs#158]
After creating a group and viewing the group from the web page, the QR code is a broken image. When I view the QR code URL I get the error:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

and logs show the errors below:
Dec  9 06:52:12 test uwsgi[44550]: #033[32m2022-12-09 06:52:12,979#033[0m #033[35mtest#033[0m #033[34msogs.web[44550]#033[0m #033[1;30mERROR#033[0m #033[31mException on /r/test/invite.png [GET]#033[0m
Dec  9 06:52:12 test uwsgi[44550]: Traceback (most recent call last):
Dec  9 06:52:12 test uwsgi[44550]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2070, in wsgi_app
Dec  9 06:52:12 test uwsgi[44550]:     response = self.full_dispatch_request()
Dec  9 06:52:12 test uwsgi[44550]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1515, in full_dispatch_request
Dec  9 06:52:12 test uwsgi[44550]:     rv = self.handle_user_exception(e)
Dec  9 06:52:12 test uwsgi[44550]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1513, in full_dispatch_request
Dec  9 06:52:12 test uwsgi[44550]:     rv = self.dispatch_request()
Dec  9 06:52:12 test uwsgi[44550]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1499, in dispatch_request
Dec  9 06:52:12 test uwsgi[44550]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Dec  9 06:52:12 test uwsgi[44550]:   File "/usr/lib/python3/dist-packages/sogs/routes/views.py", line 64, in serve_invite_qr
Dec  9 06:52:12 test uwsgi[44550]:     img = qrencode.encode(room.url)
Dec  9 06:52:12 test uwsgi[44550]:   File "/usr/lib/python3/dist-packages/qrencode/__init__.py", line 47, in encode
Dec  9 06:52:12 test uwsgi[44550]:     version, size, data = _encode(data, version, level, hint, True)
Dec  9 06:52:12 test uwsgi[44550]: SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

OS is a fresh Ubunto 20.04
Python version: 3.10.6

Followed install steps here for sogs-standalone:
https://docs.oxen.io/products-built-on-oxen/session/guides/open-group-setup

Any ideas? thx

**Comment by zcyph** [comment]
I am having the same issue with sogs-proxied in Ubuntu 22.04, tested the apt package and the manual installation, with nginx and Caddy and Python 3.10.6.

**Comment by jagerman** [comment]
It seems the issue here is a problem with something in the qrencode package (e.g. there's an Arch Linux bug report about it here: https://bugs.archlinux.org/task/73372).  I think we need to switch to qrcode rather than qrencode for generating the QR code for better compatibility.

**Comment by jagerman** [comment]
Fixed by #161
