### ISSUE TITLE
Messages posted prior to enabling id blinding are downloaded with real Session id after enabling id blinding.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-pysogs#164]
After enabling id blinding on `sog.caliban.org`, I observe that messages posted prior to blinding are still downloaded by Session with the original unblinded id.

This allows the association of blinded ids with their unblinded counterparts for any given display name.

Should id blinding not be retroactively applied to all messages downloaded from the server?

**Comment by jagerman** [comment]
Unfortunately it cannot be done retroactively because clients need to be able to verify the signature of the message (i.e. they do not have to trust SOGS as to the content of a message), but those signatures will be invalid if the poster ID is changed.

**Comment by ianmacd** [comment]
> Unfortunately it cannot be done retroactively because clients need to be able to verify the signature of the message (i.e. they do not have to trust SOGS as to the content of a message), but those signatures will be invalid if the poster ID is changed.

Understood. Thank you.
