### ISSUE TITLE
unable to locate package sogs-proxied

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-pysogs#181]
When I enter `sudo apt install sogs-proxied`
I get `unable to locate package sogs-proxied`.

What am I doing wrong? Or is the service working wrong? Extremely sorry if the question is dumb, I'm new to SOGS

![image](https://user-images.githubusercontent.com/122599546/225902755-789beea3-1ed5-4211-a4ed-9cc21141e2a9.png)

**Comment by mdPlusPlus** [comment]
Did you add the `deb.oxen.io` repository?  
What distro are you on?
