### ISSUE TITLE
Add endpoints for listing bans

### ISSUE THREAD

**Issue by jagerman** [oxen-io/session-pysogs#63]
In old SOGS there was a `/block_list` that just returns the list of all banned session IDs.  This doesn't work well for new SOGS because we have supplemental info, such as a possible ban timeout, as well as different types of restrictions (for example, someone might only be muted but not entirely banned).

We can, of course, just return a dump of the ban info, but that isn't great either because a ban list almost never shrinks, which means the returned data is going to be growing forever.

I think, instead, we need some sort of incremental ban mechanism so that moderators can query bans/permissions/etc. and receive updates to that list without needing to download the whole list every time.

**Comment by majestrate** [comment]
this would require a way to get the permission state at a given point in time so that deltas to the ban info can be paginated.
